# Workflow name
name: First Workflow 

# Events
on: workflow_dispatch


# Tasks to do
jobs: 
  first-ob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello world"
      - name: Print Working"
        run: echo "Working"
      - name: Print Goodbye"
        run: echo "Goodbye"
  second-ob:
    runs-on: ubuntu-latest
    steps:
      - name: Create Python Env
        run: |
          echo "Teskt " > plik.txt
          cat plik.txt
  run_python_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - run: | 
          echo "Repository has been clonded to the runner"
          ls ${{github.workspace}}
          cat app.py
      - name: Run code
        run: |
          pip install pytest
          cd source
          python app.py
      - name: Run tests
        run: |
          cd tests
          pytest
